#ifndef __HARKLESWARM__
#define __HARKLESWARM__

#define OUTER_BORDER_WIDTH_H 4
#define OUTER_BORDER_WIDTH_V 2
#define INNER_BORDER_WIDTH_H 4
#define INNER_BORDER_WIDTH_V 2

#endif  // __HARKLESWARM__
